# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: update-pnpm 
          command: 'curl -L https://unpkg.com/@pnpm/self-installer | sudo node'

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # Install dependencies.
      - run: pnpm install --prefer-frozen-shrinkwrap

      # Delete unused packages
      - run: pnpm store prune

      - save_cache:
          paths:
            - node_modules
            - ~/.pnpm-store
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: pnpm test -- --ci --coverage

      # publish coverage reports
      - run: cat coverage/lcov.info | pnpm run coveralls

      - store_test_results:
        path: coverage